"""feedback table

Revision ID: eb267cd80138
Revises: ef875f579a71
Create Date: 2021-05-17 10:24:45.974038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb267cd80138'
down_revision = 'ef875f579a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionbody', sa.Text(), nullable=True),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_mark'), 'question', ['mark'], unique=False)
    op.create_index(op.f('ix_question_questionbody'), 'question', ['questionbody'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answerbody', sa.Text(), nullable=True),
    sa.Column('questionid', sa.Integer(), nullable=True),
    sa.Column('answerid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['questionid'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_answerbody'), 'answer', ['answerbody'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedbackmsg', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_feedbackmsg'), 'feedback', ['feedbackmsg'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_index(op.f('ix_feedback_feedbackmsg'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_answer_answerbody'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_question_questionbody'), table_name='question')
    op.drop_index(op.f('ix_question_mark'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
